[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "slidie"
version = "0.0.1"
dependencies = []

[project.scripts]
slidie = "slidie.scripts.slidie_cmd:main"
